name: TypoScript Jobs

on: [push, pull_request]

jobs:
    tslint:
        name: TypoScript Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
            - run: composer require helmich/typo3-typoscript-lint
            - run: .Build/bin/typoscript-lint
